
package redachidoub;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @return
     *     returns java.util.List<redachidoub.Student>
     */
    @WebMethod(operationName = "ListStudents")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListStudents", targetNamespace = "http://service/", className = "redachidoub.ListStudents")
    @ResponseWrapper(localName = "ListStudentsResponse", targetNamespace = "http://service/", className = "redachidoub.ListStudentsResponse")
    @Action(input = "http://service/StudentService/ListStudentsRequest", output = "http://service/StudentService/ListStudentsResponse")
    public List<Student> listStudents();

}
